version: "3"

services:
  node1:
    image: "quantun/monero-testnet:0.1"
    build:
      context: .
    ports:
      - "127.0.0.1:18082:18082"
      - "127.0.0.1:18083:18083"
      - "127.0.0.1:28081:28081"
      - "127.0.0.1:38081:38081"
    volumes:
      - './chains:/monero/blockchain'
      - './wallets:/monero/wallets'
      - './logs:/monero/logs'
      - './entrypoint.sh:/monero/entrypoint.sh'
